// <auto-generated />
namespace TedShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class create_Mod_menu_Admod : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_Mod_menu_Admod));
        
        string IMigrationMetadata.Id
        {
            get { return "201705150517134_create_Mod_menu_Admod"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
